export const FETCH_ALL_TABLES_SUCCESS = 'FETCH_ALL_TABLES_SUCCESS';
export const FETCH_All_CHECKS_SUCCESS = 'FETCH_All_CHECKS_SUCCESS';
export const FETCH_CHECK_ITEMS_SUCCESS = 'FETCH_CHECK_ITEMS_SUCCESS';
export const FETCH_All_MENU_ITEMS_SUCCESS = 'FETCH_All_MENU_ITEMS_SUCCESS';
export const POST_CHECK_SUCCESS = 'POST_CHECK_SUCCESS';
export const CLOSE_CHECK_SUCCESS = 'CLOSE_CHECK_SUCCESS';
export const ADD_ITEM_TO_CHECK_SUCCESS = 'ADD_ITEM_TO_CHECK_SUCCESS';
export const VOID_ITEM_SUCCESS = 'VOID_ITEM_SUCCESS';